/* eslint-disable */
var PHRASES = [
  // ── Social ──────────────────────────────────────────────
  { id: 0, fr: "Je suis désolé de m'immiscer, mais j'ai juste une petite question.", en: "I'm sorry to interfere, but just a quick question.", context: "Politely interrupting" },
  { id: 1, fr: "Ça ne me regarde pas, mais je pense que tu devrais en parler.", en: "It's none of my business, but I think you should talk about it.", context: "Giving unsolicited advice" },
  { id: 2, fr: "Il faut que je te dise quelque chose, mais promets-moi de ne pas te fâcher.", en: "I need to tell you something, but promise me you won't get mad.", context: "Delivering delicate news" },
  { id: 3, fr: "Tu aurais dû me le dire plus tôt, j'aurais pu t'aider.", en: "You should have told me sooner, I could have helped you.", context: "Mild reproach" },
  { id: 4, fr: "Ça fait un bail qu'on ne s'est pas vus, il faut qu'on se rattrape !", en: "It's been ages since we last saw each other, we need to catch up!", context: "Reconnecting" },
  { id: 5, fr: "Je ne voudrais pas abuser de ton temps, mais est-ce que tu aurais deux minutes ?", en: "I don't want to take up too much of your time, but do you have two minutes?", context: "Politely requesting time" },
  { id: 6, fr: "C'est vraiment gentil de ta part, tu n'étais pas obligé.", en: "That's really kind of you, you didn't have to.", context: "Expressing gratitude" },
  { id: 7, fr: "Je t'en prie, il n'y a vraiment pas de quoi.", en: "Please, don't mention it.", context: "Deflecting thanks" },
  { id: 8, fr: "Excuse-moi de te déranger, je vois bien que tu es occupé.", en: "Sorry to bother you, I can see you're busy.", context: "Apologizing for interrupting" },
  { id: 9, fr: "On devrait remettre ça à une prochaine fois, qu'est-ce que tu en dis ?", en: "We should do this again sometime, what do you say?", context: "Suggesting a next meeting" },
  { id: 10, fr: "Je ne sais pas comment te le dire sans que ça paraisse bizarre.", en: "I don't know how to tell you without it sounding weird.", context: "Prefacing awkward news" },
  { id: 11, fr: "Je te laisse, on se tient au courant.", en: "I'll let you go, let's keep in touch.", context: "Ending a conversation" },
  { id: 12, fr: "Passe le bonjour à ta famille de ma part.", en: "Say hi to your family for me.", context: "Warm farewell" },
  { id: 13, fr: "Si jamais tu as besoin de quoi que ce soit, n'hésite surtout pas.", en: "If you ever need anything at all, don't hesitate.", context: "Offering help" },
  { id: 14, fr: "Je me suis permis de te tutoyer, j'espère que ça ne te dérange pas.", en: "I took the liberty of using 'tu' with you, I hope you don't mind.", context: "Navigating formality" },

  // ── Opinion ─────────────────────────────────────────────
  { id: 15, fr: "Franchement, je ne vois pas où est le problème.", en: "Honestly, I don't see what the problem is.", context: "Dismissing a concern" },
  { id: 16, fr: "Je ne suis pas du tout d'accord, mais je respecte ton point de vue.", en: "I completely disagree, but I respect your point of view.", context: "Polite disagreement" },
  { id: 17, fr: "Tu n'as pas tort, mais ce n'est pas aussi simple que ça.", en: "You're not wrong, but it's not as simple as that.", context: "Partial agreement" },
  { id: 18, fr: "Quand même, il faut reconnaître que ça a du mérite.", en: "Still, you have to admit it has merit.", context: "Conceding a point" },
  { id: 19, fr: "Tout dépend de quel côté on se place.", en: "It all depends on which side you look at it from.", context: "Relativizing" },
  { id: 20, fr: "J'ai beau essayer, je n'arrive pas à voir les choses de ton point de vue.", en: "No matter how hard I try, I can't see things from your point of view.", context: "Expressing difficulty" },
  { id: 21, fr: "Sans vouloir te contredire, je crois que c'est un peu plus nuancé.", en: "Not wanting to contradict you, but I think it's a bit more nuanced.", context: "Diplomatic pushback" },
  { id: 22, fr: "Je préfère ne pas m'avancer, on verra comment ça évolue.", en: "I'd rather not commit, let's see how things develop.", context: "Being cautious" },
  { id: 23, fr: "Il y a du vrai dans ce que tu dis, mais ça ne change rien au fond.", en: "There's truth in what you say, but it doesn't change the core issue.", context: "Acknowledging then pivoting" },
  { id: 24, fr: "Chacun voit midi à sa porte.", en: "Everyone sees things from their own perspective.", context: "Noting bias" },
  { id: 25, fr: "C'est bien beau tout ça, mais concrètement, on fait quoi ?", en: "That's all well and good, but concretely, what do we do?", context: "Pushing for action" },
  { id: 26, fr: "Si tu veux mon avis, ça ne vaut pas la peine de s'en faire.", en: "If you ask me, it's not worth worrying about.", context: "Offering perspective" },
  { id: 27, fr: "Au risque de me répéter, je maintiens ce que j'ai dit.", en: "At the risk of repeating myself, I stand by what I said.", context: "Holding a position" },
  { id: 28, fr: "Force est de constater que ça ne fonctionne pas comme prévu.", en: "We have to acknowledge that it's not working as planned.", context: "Facing reality" },

  // ── Emotion ─────────────────────────────────────────────
  { id: 29, fr: "Pourquoi diable quelqu'un ferait-il une chose pareille ?", en: "Why on earth would anyone do such a thing?", context: "Expressing disbelief" },
  { id: 30, fr: "J'en ai ras le bol de ces réunions interminables.", en: "I'm fed up with these endless meetings.", context: "Expressing frustration" },
  { id: 31, fr: "Si j'avais su, je m'y serais pris autrement.", en: "If I had known, I would have gone about it differently.", context: "Expressing regret" },
  { id: 32, fr: "Il ne manquait plus que ça !", en: "That's all we needed!", context: "Sarcastic exasperation" },
  { id: 33, fr: "C'est toujours la même rengaine avec toi.", en: "It's always the same old story with you.", context: "Expressing annoyance" },
  { id: 34, fr: "Tu ne crois pas que tu exagères un peu, là ?", en: "Don't you think you're overreacting a little?", context: "Challenging someone" },
  { id: 35, fr: "Ça m'a fait un bien fou, tu ne peux pas savoir.", en: "It did me a world of good, you have no idea.", context: "Expressing relief" },
  { id: 36, fr: "J'en reviens pas qu'il ait osé faire ça.", en: "I can't believe he had the nerve to do that.", context: "Shock and indignation" },
  { id: 37, fr: "Pour être honnête, je m'y attendais un peu.", en: "To be honest, I kind of expected it.", context: "Admitting expectations" },
  { id: 38, fr: "Ça me rend dingue quand les gens font semblant de ne pas comprendre.", en: "It drives me crazy when people pretend not to understand.", context: "Expressing irritation" },
  { id: 39, fr: "Je suis soulagé que ça se soit bien passé, j'étais mort d'inquiétude.", en: "I'm relieved it went well, I was worried sick.", context: "Expressing relief" },
  { id: 40, fr: "C'est un poids en moins, je respire enfin.", en: "That's a weight off my shoulders, I can finally breathe.", context: "Feeling relieved" },
  { id: 41, fr: "Je n'en peux plus, il faut que je prenne l'air.", en: "I can't take it anymore, I need some fresh air.", context: "Feeling overwhelmed" },
  { id: 42, fr: "Ça m'a pris de court, je ne m'y attendais pas du tout.", en: "It caught me off guard, I wasn't expecting it at all.", context: "Surprise" },
  { id: 43, fr: "Je ne sais plus où donner de la tête avec tout ça.", en: "I don't know which way to turn with all of this.", context: "Feeling overwhelmed" },
  { id: 44, fr: "Rien que d'y penser, ça me met hors de moi.", en: "Just thinking about it makes me furious.", context: "Simmering anger" },

  // ── Narration ───────────────────────────────────────────
  { id: 45, fr: "Bref, tout ça pour dire que je suis de ton côté.", en: "Anyway, all that to say I'm on your side.", context: "Wrapping up" },
  { id: 46, fr: "C'est pas la peine de s'énerver pour si peu.", en: "There's no point getting worked up over something so small.", context: "Calming someone" },
  { id: 47, fr: "On verra bien, de toute façon on n'a pas vraiment le choix.", en: "We'll see, in any case we don't really have a choice.", context: "Resigned acceptance" },
  { id: 48, fr: "Figure-toi qu'il a fini par démissionner sans prévenir personne.", en: "Would you believe he ended up resigning without telling anyone.", context: "Sharing surprising news" },
  { id: 49, fr: "Du coup, on s'est retrouvés à devoir tout recommencer de zéro.", en: "So we ended up having to start everything from scratch.", context: "Narrating a consequence" },
  { id: 50, fr: "J'ai failli le rappeler, mais je me suis ravisé au dernier moment.", en: "I almost called him back, but I changed my mind at the last second.", context: "Narrating hesitation" },
  { id: 51, fr: "Toujours est-il qu'on a fini par trouver une solution.", en: "The fact remains that we ended up finding a solution.", context: "Returning to the main point" },
  { id: 52, fr: "Pour te faire court, ça s'est très mal terminé.", en: "To make a long story short, it ended very badly.", context: "Summarizing" },
  { id: 53, fr: "Il faut dire que les circonstances ne jouaient pas en notre faveur.", en: "It has to be said that the circumstances weren't in our favor.", context: "Adding context" },
  { id: 54, fr: "Résultat des courses, personne n'a rien compris.", en: "At the end of the day, nobody understood anything.", context: "Summarizing an outcome" },
  { id: 55, fr: "Le comble, c'est qu'il n'était même pas au courant.", en: "The irony is that he wasn't even aware of it.", context: "Highlighting irony" },
  { id: 56, fr: "Tu sais quoi ? Je crois que c'est la meilleure chose qui pouvait arriver.", en: "You know what? I think it's the best thing that could have happened.", context: "Reframing positively" },
  { id: 57, fr: "En fin de compte, ça valait le coup d'attendre.", en: "In the end, it was worth the wait.", context: "Concluding" },
  { id: 58, fr: "Ce qui est fait est fait, on ne va pas revenir là-dessus.", en: "What's done is done, we're not going to go back over it.", context: "Moving on" },

  // ── Argument ────────────────────────────────────────────
  { id: 59, fr: "À ta place, je n'hésiterais pas une seconde.", en: "If I were you, I wouldn't hesitate for a second.", context: "Encouraging someone" },
  { id: 60, fr: "Ce n'est qu'une question de temps avant que ça se sache.", en: "It's only a matter of time before it comes out.", context: "Warning" },
  { id: 61, fr: "Encore faut-il que les gens soient prêts à faire des compromis.", en: "People still need to be willing to compromise, though.", context: "Adding a condition" },
  { id: 62, fr: "Je ne dis pas le contraire, mais il y a des limites.", en: "I'm not saying otherwise, but there are limits.", context: "Setting boundaries" },
  { id: 63, fr: "Que tu le veuilles ou non, c'est comme ça.", en: "Whether you like it or not, that's how it is.", context: "Stating a hard truth" },
  { id: 64, fr: "Loin de moi l'idée de te critiquer, mais tu aurais pu mieux faire.", en: "Far be it from me to criticize you, but you could have done better.", context: "Softened criticism" },
  { id: 65, fr: "Mettons les choses au clair une bonne fois pour toutes.", en: "Let's set the record straight once and for all.", context: "Demanding clarity" },
  { id: 66, fr: "Il n'empêche que ça pose un vrai problème de fond.", en: "That doesn't change the fact that it raises a real underlying problem.", context: "Insisting on an issue" },
  { id: 67, fr: "On ne peut pas continuer à fermer les yeux là-dessus.", en: "We can't keep turning a blind eye to this.", context: "Calling for action" },
  { id: 68, fr: "C'est un argument qui se défend, je te l'accorde.", en: "That's a defensible argument, I'll give you that.", context: "Conceding" },
  { id: 69, fr: "Soyons réalistes, ça n'arrivera jamais dans les délais.", en: "Let's be realistic, it will never happen on time.", context: "Pragmatic pushback" },
  { id: 70, fr: "À force de repousser, on va finir par ne jamais le faire.", en: "If we keep putting it off, we'll end up never doing it.", context: "Urging action" },
  { id: 71, fr: "Je veux bien faire un effort, mais il faut que ce soit réciproque.", en: "I'm willing to make an effort, but it has to be mutual.", context: "Negotiating" },
  { id: 72, fr: "On tourne en rond, il faut trancher.", en: "We're going in circles, we need to make a decision.", context: "Cutting through debate" },

  // ── Daily ───────────────────────────────────────────────
  { id: 73, fr: "J'ai un empêchement de dernière minute, est-ce qu'on peut décaler ?", en: "Something came up last minute, can we reschedule?", context: "Rescheduling" },
  { id: 74, fr: "Je passe te prendre vers huit heures, ça te va ?", en: "I'll pick you up around eight, does that work?", context: "Making arrangements" },
  { id: 75, fr: "Ce n'est pas donné, mais ça vaut vraiment le coup.", en: "It's not cheap, but it's really worth it.", context: "Evaluating a purchase" },
  { id: 76, fr: "J'ai complètement oublié de te rappeler, je suis impardonnable.", en: "I completely forgot to call you back, I'm unforgivable.", context: "Apologizing" },
  { id: 77, fr: "La prochaine fois, je m'en occupe, ne t'inquiète pas.", en: "Next time, I'll take care of it, don't worry.", context: "Taking responsibility" },
  { id: 78, fr: "Je suis en retard, le temps de trouver une place et j'arrive.", en: "I'm running late, just finding a parking spot and I'll be there.", context: "Running late" },
  { id: 79, fr: "Ça ne me dit rien du tout, on pourrait faire autre chose ?", en: "I don't feel like it at all, could we do something else?", context: "Declining politely" },
  { id: 80, fr: "J'ai la flemme de cuisiner ce soir, on commande quelque chose ?", en: "I can't be bothered to cook tonight, shall we order something?", context: "Casual suggestion" },
  { id: 81, fr: "Tu pourrais me rendre un petit service, si ça ne t'embête pas ?", en: "Could you do me a small favor, if you don't mind?", context: "Asking a favor" },
  { id: 82, fr: "Ça tombe bien, j'allais justement t'en parler.", en: "Perfect timing, I was just about to bring that up.", context: "Happy coincidence" },
  { id: 83, fr: "Je me suis trompé de rue, je suis complètement perdu.", en: "I took the wrong street, I'm completely lost.", context: "Being lost" },
  { id: 84, fr: "Il fait un froid de canard, on ferait mieux de rentrer.", en: "It's freezing cold, we'd better go back inside.", context: "Commenting on weather" },
  { id: 85, fr: "Je ne suis pas d'humeur à sortir ce soir, une autre fois peut-être.", en: "I'm not in the mood to go out tonight, another time maybe.", context: "Declining an invitation" },
  { id: 86, fr: "On est arrivés pile à l'heure, pour une fois.", en: "We arrived right on time, for once.", context: "Noting punctuality" },
  { id: 87, fr: "Ce n'est pas grave, ça arrive à tout le monde.", en: "It's no big deal, it happens to everyone.", context: "Reassuring" },
  { id: 88, fr: "J'ai un trou de mémoire, ça me reviendra.", en: "I'm having a memory lapse, it'll come back to me.", context: "Forgetting something" },

  // ── Work & Professional ─────────────────────────────────
  { id: 89, fr: "Je me permets de revenir vers vous au sujet de notre dernier échange.", en: "I'm getting back to you regarding our last conversation.", context: "Professional follow-up" },
  { id: 90, fr: "Ça ne relève pas de mes compétences, mais je peux te mettre en contact.", en: "That's outside my area, but I can put you in touch with someone.", context: "Redirecting" },
  { id: 91, fr: "On est débordés en ce moment, il va falloir prioriser.", en: "We're swamped right now, we'll need to prioritize.", context: "Managing workload" },
  { id: 92, fr: "J'ai pris du retard sur ce dossier, je m'en excuse.", en: "I've fallen behind on this file, I apologize.", context: "Professional apology" },
  { id: 93, fr: "Sauf erreur de ma part, on avait convenu d'un autre arrangement.", en: "Unless I'm mistaken, we had agreed on a different arrangement.", context: "Politely correcting" },
  { id: 94, fr: "Je fais au mieux, mais je ne peux pas tout gérer tout seul.", en: "I'm doing my best, but I can't handle everything on my own.", context: "Setting limits" },
  { id: 95, fr: "Ce n'est pas dans mes habitudes de me plaindre, mais là c'est trop.", en: "I don't usually complain, but this is too much.", context: "Lodging a complaint" },
  { id: 96, fr: "N'hésitez pas à me relancer si vous n'avez pas de retour de ma part.", en: "Don't hesitate to follow up if you don't hear back from me.", context: "Professional courtesy" },

  // ── Idiomatic Expressions ───────────────────────────────
  { id: 97, fr: "On n'est pas sortis de l'auberge.", en: "We're not out of the woods yet.", context: "Acknowledging ongoing difficulty" },
  { id: 98, fr: "Ce n'est pas la mer à boire, tu vas y arriver.", en: "It's not the end of the world, you'll manage.", context: "Encouraging" },
  { id: 99, fr: "Il ne faut pas mettre la charrue avant les bœufs.", en: "We shouldn't put the cart before the horse.", context: "Urging patience" },
  { id: 100, fr: "Autant chercher une aiguille dans une botte de foin.", en: "It's like looking for a needle in a haystack.", context: "Describing futility" },
  { id: 101, fr: "Il vaut mieux tard que jamais, comme on dit.", en: "Better late than never, as they say.", context: "Philosophical acceptance" },
  { id: 102, fr: "C'est en forgeant qu'on devient forgeron.", en: "Practice makes perfect.", context: "Encouraging persistence" },
  { id: 103, fr: "Après la pluie, le beau temps.", en: "Every cloud has a silver lining.", context: "Offering comfort" },
  { id: 104, fr: "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué.", en: "Don't count your chickens before they hatch.", context: "Warning against premature celebration" },
  { id: 105, fr: "Qui vivra verra, ce n'est pas la peine de spéculer.", en: "Time will tell, there's no point speculating.", context: "Philosophical patience" },
  { id: 106, fr: "On ne fait pas d'omelette sans casser des œufs.", en: "You can't make an omelette without breaking eggs.", context: "Accepting trade-offs" },

  // ── Nuanced / Sophisticated ─────────────────────────────
  { id: 107, fr: "Il y a anguille sous roche, je ne lui fais pas confiance.", en: "Something's fishy, I don't trust him.", context: "Expressing suspicion" },
  { id: 108, fr: "C'est à double tranchant, il faut peser le pour et le contre.", en: "It's a double-edged sword, we need to weigh the pros and cons.", context: "Analyzing risk" },
  { id: 109, fr: "Je marche sur des œufs avec ce sujet, c'est très délicat.", en: "I'm walking on eggshells with this topic, it's very sensitive.", context: "Navigating sensitivity" },
  { id: 110, fr: "On remet les pendules à l'heure : voilà ce qui s'est vraiment passé.", en: "Let's set the record straight: here's what actually happened.", context: "Correcting a narrative" },
  { id: 111, fr: "Ça sent le roussi, je crois qu'on va avoir des problèmes.", en: "I smell trouble, I think we're going to have problems.", context: "Sensing danger" },
  { id: 112, fr: "Il a retourné sa veste du jour au lendemain, sans la moindre explication.", en: "He did a complete U-turn overnight, without the slightest explanation.", context: "Describing betrayal" },
  { id: 113, fr: "Ce n'est que la partie visible de l'iceberg.", en: "That's just the tip of the iceberg.", context: "Suggesting hidden depth" },
  { id: 114, fr: "Il a le don de mettre les pieds dans le plat.", en: "He has a knack for putting his foot in his mouth.", context: "Describing tactlessness" },
  { id: 115, fr: "On a tourné la page, il est temps de passer à autre chose.", en: "We've turned the page, it's time to move on.", context: "Closure" },
  { id: 116, fr: "Mieux vaut prévenir que guérir, surtout dans ce genre de situation.", en: "Better safe than sorry, especially in this kind of situation.", context: "Advocating caution" },
  { id: 117, fr: "Je donne ma langue au chat, je ne vois vraiment pas.", en: "I give up, I really can't figure it out.", context: "Admitting defeat" },
  { id: 118, fr: "Il faut battre le fer tant qu'il est chaud.", en: "We need to strike while the iron is hot.", context: "Urging timely action" },
  { id: 119, fr: "Les murs ont des oreilles, fais attention à ce que tu dis.", en: "The walls have ears, be careful what you say.", context: "Warning about eavesdropping" },
  { id: 120, fr: "J'ai d'autres chats à fouetter pour le moment.", en: "I have bigger fish to fry right now.", context: "Expressing priorities" },
  { id: 121, fr: "Ça ne casse pas trois pattes à un canard, mais c'est correct.", en: "It's nothing special, but it's decent.", context: "Lukewarm praise" },
  { id: 122, fr: "Il pleut des cordes, on ferait mieux de rester ici.", en: "It's raining cats and dogs, we'd better stay here.", context: "Weather decision" },
  { id: 123, fr: "Je n'y suis pour rien, c'est pas moi qui ai décidé.", en: "It's not my fault, I'm not the one who decided.", context: "Deflecting blame" },
  { id: 124, fr: "C'est un coup d'épée dans l'eau, ça ne changera rien.", en: "It's a waste of effort, it won't change anything.", context: "Futility" },
  { id: 125, fr: "On fera avec les moyens du bord.", en: "We'll make do with what we've got.", context: "Pragmatic acceptance" },
  { id: 126, fr: "Prenons le taureau par les cornes et réglons ça maintenant.", en: "Let's take the bull by the horns and sort this out now.", context: "Decisive action" },
  { id: 127, fr: "Ce n'est pas tombé dans l'oreille d'un sourd.", en: "It didn't fall on deaf ears.", context: "Confirming attention" },
  { id: 128, fr: "Il faut savoir raison garder, même quand c'est difficile.", en: "We must keep a level head, even when it's hard.", context: "Advocating composure" },
  { id: 129, fr: "Tant pis, ce sera pour une autre fois.", en: "Too bad, it'll be for another time.", context: "Accepting a missed opportunity" }
];
